name: Validacao ApoioMicro CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Instalar Dependências
        run: npm install

      - name: Executar Análise Estática (Linting)
        run: npm run lint

      - name: Executar Testes Automatizados
        run: npm test
